spring.application.name=blogger

spring.app.authKey=__SecretKey__

spring.app.jwtSecret=VPZwiwVpKxvtdKl8XvrHtKSjtdFKhdsR
spring.app.jwtExpirationMs=30000000

spring.app.jwtCookieName=blogger-cookie

frontend.url=http://localhost:5173
image.base.url=http://localhost:8080/images